import { makeStyles } from 'tss-react/mui';
import { IProps } from './ErrorScreen.types';

export const useStyles = makeStyles()((theme) => ({
  rootContainer: {
    height: '100vh',
    width: '100vw',
    // margin: '-1rem',
    backgroundColor: theme.palette.colors.gray[25],
    display: 'grid',
    placeItems: 'center',
    justifyContent: 'center',
    zIndex: 10000,
    position: 'fixed',
    inset: 0,
  },
  loaderContainer: {
    width: '378px',
    height: '320px',
    boxSizing: 'border-box',
    padding: '36px 48px',
    background: theme.palette.colors.system.white,
    boxShadow: '2px 2px 54px rgba(0,0,0,0.05)',
    borderRadius: '24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageBox: {},
  loaderBox: {
    border: `1px solid ${theme.palette.colors.gray[900]}`,
    borderRadius: '8px',
    width: '100%',
    padding: '12px',
    '& .MuiLinearProgress-root': {
      boxShadow: 'none',
      background: 'none!important',
      height: '3px !important',
    },
    '& .MuiLinearProgress-bar': {
      background: `${theme.palette.colors.gray[900]} !important`,
    },
  },
  loaderMessageBox: {
    marginTop: '32px',
  },
  rootContainer1: {
    height: '100vh',
    width: '100vw',
    // margin: '-1rem',
    backgroundColor: 'rgb(0 0 0 / 18%)',
    display: 'grid',
    placeItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    padding: '36px',
    zIndex: 10000,
    position: 'fixed',
    inset: 0,
    "&[data-min-screen='true']": {
      display: 'none !important',
      '@media (max-width: 350px)': {
        display: 'grid !important',
      },
    },
  },
  errorContainer: {
    boxSizing: 'border-box',
    maxWidth: '969.42px',
    padding: '36px 48px',
    background: theme.palette.colors.system.white,
    boxShadow: '2px 2px 54px rgba(0,0,0,0.05)',
    borderRadius: '24px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '60px',
    position: 'relative',
    zindex: 10000,
    '@media (max-width: 800px)': {
      flexDirection: 'column',
    },
  },
  errorContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  errorHeader: {
    color: theme.palette.colors.gray[900],
    fontSize: '28px',
    marginBottom: '12px',
  },
  errorSubHeader: {
    color: theme.palette.colors.gray[400],
    marginBottom: '28px',
  },
  errorMessage2: {
    color: theme.palette.colors.gray[500],
    marginBottom: '16px',
  },
  errorContainerScreen: {
    boxSizing: 'border-box',
    width: '288px',
    padding: '32px',
    background: theme.palette.colors.system.white,
    boxShadow: '2px 2px 54px rgba(0,0,0,0.05)',
    borderRadius: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
    position: 'relative',
    zindex: 10000,
  },
  errorContentScreen: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '4px',
  },
}));
