import { makeStyles } from 'tss-react/mui';
// TODO jss-to-tss-react codemod: usages of this hook outside of this file will not be converted.
export const useStyles = makeStyles()((theme) => ({
  messageBox: {
    width: '100%',
    //boxShadow: "2px 2px 54px rgba(0, 0, 0, 0.14);",
  },
  border0T16B: {
    borderRadius: '0px 0px 16px 16px',
    //borderTop: "1px solid #2C2C2C",
  },
  messageGrid: {
    marginTop: 'auto',
    minHeight: '88px',
    //padding: "20px",
    background: theme.palette.colors.system.white,
    boxSizing: 'border-box',
    width: '100%',
    position: 'relative',
    zIndex: 101,
    display: 'flex',
    // gridTemplateColumns: "24px calc(100% - 32px - 48px - 24px) 48px",
    gap: '16px',
    alignItems: 'center',
  },
  subWrapper: {
    display: 'flex',
    boxShadow: '0px 4px 24px rgba(0, 0, 0, 0.05);',
    border: '1px solid ' + theme.palette.colors.gray[50],
    borderRadius: '4px',
    height: '100%',
  },
  input: {
    color: '#252427',
    // fontFamily: 'Inter',
    fontSize: '16px',
    lineHeight: '19px',
    fontWeight: 400,
    outline: 'none !important',
    margin: '11.5px 8px 8px',
    zIndex: 1,
    flex: 1,
    width: 'calc(100% - 80px)',
    maxHeight: '76px',
    overflow: 'auto',
    border: 'none',
    wordWrap: 'break-word',
    wordBreak: 'break-word',
    whiteSpace: 'pre-wrap',
    backgroundColor: 'transparent',
    minHeight: '30px',
    paddingTop: '3px',
  },
  middleContainer: {
    flex: 1,
  },
  questionstyle: {
    //position: "absolute",
    color: '#5C5A61',
    margin: '0px 8px',
    zIndex: 1,
    flex: 1,
    width: 'calc(100% - 20px)',
    maxHeight: '76px',
    overflow: 'auto',
    border: 'none',
    overflowWrap: 'anywhere',
    // wordWrap: "break-word",
    //whiteSpace: "pre-wrap",
  },
  questionCon: {
    maxHeight: '76px',
    width: 'calc(100% - 20px)',
    overflow: 'auto',
  },
  placeholderSpan: {
    color: '#AEAEAE',
    // fontFamily: 'Inter',
    fontSize: '16px',
    lineHeight: '19px',
    fontWeight: 400,
    position: 'absolute',
  },
  visibilty: {
    visibility: 'visible',
    zIndex: 2,
    pointerEvents: 'none',
    top: '34px',
    left: '10px',
    userSelect: 'none',
  },
  visibiltyNone: {
    visibility: 'hidden',
    pointerEvents: 'none',
    userSelect: 'none',
  },
  sendIcon: {
    background: '#252427',
    height: '48px',
    width: '48px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    borderRadius: '4px',
    '& svg': {
      height: '24px',
      width: '24px',
      '& path': {
        fill: '#FFFFFF',
      },
    },
  },
  disableSend: {
    background: theme.palette.colors.gray[400],
    height: '48px',
    width: '48px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    borderRadius: '4px',
    '& svg': {
      height: '24px',
      width: '24px',
      '& path': {
        fill: theme.palette.colors.gray[100],
      },
    },
  },
  tagOptions: {
    position: 'absolute',
    bottom: '0px',
    cursor: 'pointer',
  },
  displayFlexColumn: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    position: 'relative',
    //border:"red 1px solid"
  },
  tagDiv: {
    backgroundColor: '#FFFFFF',
    padding: '0px 16px',
    boxSizing: 'border-box',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
  },

  tagDiv2: {
    backgroundColor: '#F8F8F8',
    padding: '8px 6px',
    boxSizing: 'border-box',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    borderRadius: '6px',
  },
  scrollDownButton: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    background: '#E1E1E1',
    position: 'absolute',
    cursor: 'pointer',
    top: '-100px',
    right: '20px',
    zIndex: 0,
  },
  center: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
}));
