import { makeStyles } from 'tss-react/mui';
import {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  CANVAS_XOFFSET,
  DRAGGABLE_BAR_MAX,
  DRAGGABLE_BAR_WIDTH,
  STYLES,
} from '../DiagnosticCondition.utils';

export const useStyles = makeStyles<any>()((theme, props) => ({
  scrollBody: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    overflowY: 'auto',
    overflowX: 'hidden',
    margin: `0 -${STYLES.scrollXPadding}px`,
    padding: `0 ${STYLES.scrollXPadding}px 36px ${STYLES.scrollXPadding}px`,
  },
  canvasAccordion: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    '& .diagnosticIcon': {
      position: 'relative',
      // zIndex: 1000,
      display: 'inline-block',
      background: theme.palette.colors.gray[25],
      padding: '4px 0',
      cursor: 'pointer',
    },
  },
  bottomButtonWrapper: {
    margin: '28px 0 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '15px',
    '& .MuiButton-root': {
      padding: '0 !important',
    },
    '& .MuiButton-label': {
      fontWeight: '600 !important',
    },
  },
  draggableBarArea: {
    width: `${CANVAS_WIDTH}px`,
    marginLeft: `${CANVAS_XOFFSET - STYLES.scrollXPadding}px`,
    position: 'relative',
    height: '10px',
    // background: 'orange',
  },
  draggableBar: {
    boxSizing: 'border-box',
    position: 'absolute',
    top: '-20px',
    left: `${DRAGGABLE_BAR_MAX}px`,
    width: `${DRAGGABLE_BAR_WIDTH}px`,
    height: '100vh',
    background: 'rgb(255 255 255 / 70%)',
    // border: "0.5px solid #FFF",
    boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25), inset 0px 0px 2px rgba(0, 0, 0, 0.25)',
    borderBottom: 'none',
    cursor: 'move',
    zIndex: 100,
    borderTopRightRadius: '30px',
    borderTopLeftRadius: '30px',
    touchAction: 'none',
  },
  dragIcon: {
    display: 'inline-block',
    visibility: 'hidden',
    pointerEvents: 'none',
    translate: '-50%',
    marginLeft: `${DRAGGABLE_BAR_WIDTH / 2}px`,
    // scale: 0.8,
    cursor: 'grab',
    touchAction: 'none',
  },
  focusLabel: {
    pointerEvents: 'none',
    touchAction: 'none',
    position: 'absolute',
    top: '-8px',
    left: '50%',
    translate: '-50% -100%',
    padding: '4px 8px 4px 8px',
    borderRadius: '4px',
    backgroundColor: theme.palette.colors.system.white,
    boxShadow: '0px 8px 12px 0px #00000014',
    transition: 'opacity .3s ease-in-out',
    opacity: 0,
    whiteSpace: 'nowrap',
  },
  graphBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    margin: '10px 0',
  },
  biomarkerName: {
    color: theme.palette.colors.gray[900],
  },
  questionGrapBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    margin: '32px 0',
  },
}));
