import { makeStyles } from "tss-react/mui";

export const useStyles = makeStyles()((theme, _params, classes) => ({
  chatComponent: {
    height: "inherit",
    background: theme.palette.background.default,
    width: "inherit",
    display: "flex",
    flexDirection: "column",
  },
  chatBody: {
    flex: "auto",
  },
  hrMargin: {
    margin: "5px 0px",
    border: "1px solid #575757",
  },
  textArea: {
    boxSizing: "border-box",
    flex: "1 1 auto",
    width: "inherit",
    minWidth: "0",
    minHeight: "20px",
    fontSize: "15px",
    fontWeight: 400,
    lineHeight: "20px",
    outline: "none",
    willChange: "width",
    padding: "9px 12px 11px",
    margin: "5px 10px",
    backgroundColor: "#33383b",
    border: "1px solid #33383b",
    borderRadius: "21px",
  },
  chatFooter: {
    backgroundColor: "#141415",
    width: "100%",
    position: "relative",
  },
  chatFooterFlex: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    maxWidth: "100%",
  },
  sendIcon: {
    fill: "rgb(0, 255, 194)",
    width: "37px",
    height: "37px",
    margin: "auto 2px",
    cursor: "pointer",
  },
  spanCenter: {
    display: "block",
    margin: "auto",
  },
  chatHead: {
    margin: "2px 0px 5px 0px",
    fontWeight: 600,
    color: "#00FFc2",
    //fontfamily: 'Inter',
    fontStyle: "normal",
    lineHeight: "12px",
    fontSize: "12px !important",
  },
  chatBodyMessages: {
    overflowX: "hidden",
    overflowY: "auto",
    width: "100%",
    height: "100%",
    background: theme.palette.background.default,
    position: "relative",
  },
  chatBodyTop: {
    flex: "1 1 auto",
    minHeight: "12px",
  },
  chatBodyBottom: {
    paddingBottom: "8px",
    flex: "0 0 auto",
  },
  noConditions: {
    display: "block",
    top: "42%",
    left: "25%",
    width: "50%",
    margin: "auto",
    textAlign: "center",
    color: "#fff",
    wordBreak: "break-word",
  },
  fullWidthHeight: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
  },
  daySpan: {
    display: "block",
    margin: "auto",
    width: "max-content",
    padding: "5px 14px",
    color: "#A0A0A0",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "12px",
    lineHeight: "150%",
  },
  dayDiv: {
    display: "grid",
    gridTemplateColumns: "auto max-content auto",
  },
  dayHr: {
    width: "100%",
    border: "1px solid #353535",
  },
  chatMessage: {
    position: "relative",
    margin: "3px 5px 3px 5px",
    flexDirection: "column",
    float: "left",
    minWidth: "140px",
    width: "calc(100% - 10px)",
  },
  replyMessage: {
    position: "relative",
    margin: "3px 5px",
    flexDirection: "column",
    float: "left",
    minWidth: "140px",
    width: "calc(100%)",
  },
  chatMessageContent: {
    boxShadow: "1px 1px 1px 1px rgb(0 0 0 / 20%)",
    padding: "0px",
    width: "100%",
  },
  MessageActions: {
    display: "none",
    cursor: "pointer",
    margin: "0px 10px",
    color: "#ffffff",
    fontSize: "14px",
  },
  paddingDivTop: {
    padding: "6px 0px 0px 0px",
  },
  padding7pxL: {
    paddingLeft: "7px",
    paddingRight: "7px",
  },
  padding5pxL: {
    paddingLeft: "5px",
    paddingRight: "5px",
  },
  paddingDivBottom: {
    padding: "0px 9px 8px 9px",
  },
  paddingDivCenter: {
    padding: "0px 9px",
  },
  chatMessageGrid: {
    display: "grid",
    gridTemplateColumns: "40px calc(75% - 40px) 25%",
    alignItems: "center",
    gridGap: "4px",
  },
  leftTime: {
    textAlign: "right",
    color: "rgba(0, 0, 0, 0.45)",
    fontSize: "12px",
    position: "absolute",
    right: "10px",
    bottom: "5px",
  },
  avatar: {
    width: "35px",
    height: "35px",
    color: "black",
  },
  avatarPlaceBottom: {
    display: "block",
    margin: "auto auto 0px auto",
  },
  loadMoreSpan: {
    "&:hover": {
      textDecoration: "underline",
      cursor: "pointer",
    },
  },
  leftAlign: {
    textAlign: "right",
    //fontfamily: 'Inter',
    fontStyle: "normal",
    fontSize: "10px",
    lineHeight: "12px",
    fontWeight: "normal",
    color: theme.palette.text.primary,
  },
  marginB5: {
    marginBottom: "5px",
  },
  sendDisable: {
    fill: "#A0A0A0",
    stroke: "#A0A0A0",
    cursor: "revert",
  },
  attachmentIcon: {
    fill: "rgb(0, 255, 194)",
    width: "26px",
    height: "26px",
    margin: "auto 8px",
    transform: "rotateZ(220deg)",
    cursor: "pointer",
  },
  attachDisable: {
    fill: "#A0A0A0",
  },
  headerContainer: {
    backgroundColor: theme.palette.background.default,
    borderRadius: "8px 8px 0px 0px",
    // width: '100%',
    boxShadow: "0px 4px 4px rgb(0 0 0 / 25%)",
    display: "grid",
  },
  titleContainer: {
    marginRight: "10px",
    width: "auto",
    //fontfamily: 'Inter',
    fontWeight: 500,
    fontStyle: "normal",
    fontSize: "18px",
    lineHeight: "24px",
    color: "#00FFC2",
    flexGrow: 2,
  },
  chatAttachments: {
    zIndex: 5,
    width: "inherit",
    position: "absolute",
    bottom: "60px",
    borderRadius: "8px 8px 0px 0px",
    background: theme.palette.background.paper,
  },
  chatSuggestions: {
    zIndex: 2,
    width: "inherit",
    position: "absolute",
    bottom: "60px",
    borderRadius: "8px 8px 0px 0px",
    background: theme.palette.background.paper,
    maxHeight: "calc(100% - 70%)",
    overflow: "auto",
  },
  chatScroll: {
    zIndex: 1,
    width: "inherit",
    position: "absolute",
    bottom: "60px",
    maxHeight: "calc(100% - 70%)",
    float: "right",
  },
  bottomZero: {
    zIndex: 2,
    width: "inherit",
    position: "absolute",
    bottom: "0px",
    borderRadius: "8px",
    background: theme.palette.background.paper,
    padding: "10px",
  },
  attachmentPreview: {
    width: "calc(100% - 14px)",
    height: "100px",
    background: "rgba(196, 196, 196, 0.5)",
    borderRadius: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "10px",
    margin: "auto",
  },
  filenameView: {
    display: "grid",
    gridTemplateColumns: "35px 83%",
    width: "calc(100% - 14px)",
  },
  marginLeft13px: {
    margin: "13px auto 0px auto",
  },
  extentionSpan: {
    height: "35px",
    width: "35px",
    border: "1px solid " + theme.palette.text.primary,
    borderRadius: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "10px",
    lineHeight: "12px",
    wordBreak: "break-all",
  },
  filename: {
    margin: "5px",
    fontSize: "14px",
    lineHeight: "15px",
  },
  downloadButton: {
    cursor: "pointer",
  },
  calloutTeam: {
    fontSize: "12px",
    lineHeight: "150%",
    color: "#FF9E0E",
    marginRight: "5px",
  },
  calloutMe: {
    fontSize: "12px",
    lineHeight: "150%",
    color: theme.palette.primary.main,
    marginRight: "5px",
  },
  notesForMe: {
    backgroundColor: "#0E0E0E !important",
  },
  taggedPerson: {
    color: "#34B7F1",
  },
  loader: {
    color: "rgb(255, 255, 255)",
    width: "17px !important",
    height: "17px !important",
    marginRight: "15px",
  },
  flexGrow100: {
    display: "flex",
    flexGrow: 100,
  },
  replyBody: {
    background: "#2C2C2C",
    borderRadius: "5px",
    padding: "6px 9px 9px 9px",
  },
  replyHeight: {
    maxHeight: "40px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    whiteSpace: "normal",
  },
  searchHighLight: {
    background: "rgba(0, 98, 78, 0.25)",
  },
  pointer: {
    cursor: "pointer",
    display: "block",
    margin: "auto",
  },
  scrollIcon: { float: "right", cursor: "pointer" },
  readMore: {
    color: "#34B7F1",
    cursor: "pointer",
  },
  unreadMessages: {
    background: theme.palette.background.paper,
    marginTop: "20px",
    marginBottom: "10px",
    color: theme.palette.text.primary,
  },
  unreadMessagesBadge: {
    minWidth: "24px",
    height: "24px",
    fontSize: "12px",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    borderRadius: "12px",
    backgroundColor: theme.palette.primary.main,
    position: "relative",
    top: "15px",
    left: "-7px",
    padding: "4px",
    width: "fit-content",
    zIndex: 1,
    justifyContent: "center",
  },
  messageContent: {
    fontSize: "14px !important",
  },
  messageSenderText: {
    fontSize: "12px !important",
    marginBottom: "5px",
  },
  rightMessageWidth: {
    width: "calc(75% - 40px)",
    padding: "6px 5px 8px 5px",
  },
  messageContainer: {
    display: "flex",
    overflowX: "hidden",
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    [`&:hover .${(classes as any).MessageActions}`]: {
      display: "block",
    },
  },
  highlight: {
    backgroundColor: "#ffffff",
    color: "#015874",
  },
  rceMboxText: {
    color: "#ffffff",
    //fontfamily: 'Inter',
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "20px",
    "&::after": {
      content: "none !important",
    },
  },
  rceMboxRightFirst: {
    borderRadius: "5px 0px 5px 5px !important",
  },
  rceMboxRightNormal: {
    borderRadius: "5px 5px 5px 5px !important",
  },
  rceMboxRight: {
    paddingTop: "9px !important",
    background: "#00493B !important",
    marginRight: "30px !important",
    border: "5px !important",
    width: "225px",
  },
  rceMboxLeftFirst: {
    borderRadius: "0px 5px 5px 5px !important",
  },
  rceMboxLeftNormal: {
    borderRadius: "5px 5px 5px 5px !important",
  },
  rceMboxLeft: {
    background: "#3F4040 !important",
  },
  rceMbox: {
    position: "relative",
    background: "#FFFFFF",
    borderRadius: "5px",
    boxShadow: "1px 1px 1px 1px rgb(0 0 0 / 20%)",
    borderTopLeftRadius: "0px",
    marginLeft: "20px",
    marginRight: "5px",
    marginTop: "3px",
    flexDirection: "column",
    marginBottom: "3px",
    padding: "0px",
    float: "left",
    minWidth: "140px",
  },
  rightmessageDate: {
    margin: "0px 9px 8px 9px",
  },
}));
