import { makeStyles } from 'tss-react/mui';

// TODO jss-to-tss-react codemod: usages of this hook outside of this file will not be converted.
export const useStyles = makeStyles()((theme) => ({
  modalWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '25px',
    marginBottom: '10px',
  },
  body: {
    background: '#FFFFFF',
    height: 'calc(100% - 0px)',
    display: 'grid',
    gridTemplateRows: 'calc(100% - 78px) 78px',
    position: 'relative',
  },
  recipePanelWrap: {
    overflowY: 'auto',
    overflowX: 'hidden',
    height: '100%',
    padding: '0px 0px 18px 0px',
    '& .clamp': {
      // flexDirection: "column !important",
      flexDirection: 'column',
    },
    '& .featureText': {
      maxWidth: '100% !important',
      width: '100% !important',
    },
    position: 'relative',
  },
  footerButton: {
    margin: '8px',
  },
  figureWrap: {
    margin: '0px',
    position: 'relative',
    height: '280px',
    overflow: 'hidden',
    '& img': {
      maxWidth: '100%',
      width: '100%',
      display: 'block',
      height: '100%',
    },
    '&:before': {
      content: "''",
      position: 'absolute',
      top: '0px',
      left: '0px',
      bottom: '0px',
      right: '0px',
      zIndex: 1,
      background: 'rgba(0,0,0,0.3)',
    },
  },
  bookmarks: {
    display: 'flex !important',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#373639',
    height: '36px',
    width: '36px',
    top: '9px',
    right: '20px',
    position: 'absolute !important' as any,
    zIndex: 3,
    borderRadius: '6px',
    cursor: 'pointer',
  },
  arrowLeft: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#FFFFFF',
    height: '24px',
    width: '24px',
    top: '107px',
    left: '6px',
    position: 'absolute',
    zIndex: 2,
    borderRadius: '18px',
    cursor: 'pointer',
    // opacity: '0.6',
    '&svg': {
      '&path': {
        fill: '#252427 !important',
      },
    },
    '& path': {
      fill: '#252427 !important',
    },
  },
  arrowRight: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '24px',
    width: '24px',
    top: '107px',
    right: '6px',
    position: 'absolute',
    zIndex: 2,
    borderRadius: '18px',
    cursor: 'pointer',
    // opacity: '0.6',
    rotate: '180deg',
    '&svg': {
      '&path': {
        fill: '#252427 !important',
      },
    },
    '& path': {
      fill: '#252427 !important',
    },
  },
  arrowEnable: {
    opacity: '0.6',
  },
  arrowDisable: {
    opacity: '0.3',
  },
  backBtn: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#373639',
    height: '36px',
    width: '36px',
    top: '9px',
    left: '20px',
    position: 'absolute',
    zIndex: 3,
    borderRadius: '6px',
    cursor: 'pointer',
  },
  iconWrapper: {
    left: '5px',
    zIndex: 2,
    position: 'absolute',
    top: '70%',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  foodProperties: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '4px 8px',
    background: 'rgba(37, 36, 39, 0.5)',
    color: '#fff',
    borderRadius: '12px',
    marginRight: '10px',
  },
  iconWrap: {
    display: 'inline-block',
    marginRight: '5px',
    position: 'relative',
    // top: "2px",
  },
  recipeContentWrap: {
    position: 'relative',
    // height: 'calc(100% - 260px)',
    '&:before': {
      content: "''",
      position: 'absolute',
      width: '100%',
      height: '50px',
      background: '#fff',
      borderTopRightRadius: '30px',
      borderTopLeftRadius: '30px',
      top: '-38px',
      left: '0px',
      zIndex: 2,
    },
  },
  contentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    top: '-24px',
    width: '91%',
    zIndex: 3,
    padding: '0px 20px',
  },
  contentTag: {
    height: '16px',
    // width: "50px",
    borderRadius: '8px',
    color: '#5C5A61',
    border: '1px solid #5C5A61',
    padding: '0px 5px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '14px !important',
  },
  contentEasyTag: {
    color: '#5C5A61',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconEasy: {
    display: 'inline-block',
    marginRight: '8px',
    position: 'relative',
    top: '2px',
  },
  contentWrap: {
    padding: '5px 20px',
    display: 'grid',
    height: '100%',
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  title: {
    color: '#252427',
    marginBottom: '6px',
    marginTop: '8px',
    wordBreak: 'break-word',
  },
  caption: {
    color: '#5C5A61',
    wordBreak: 'break-word',
  },
  propertiesWrap: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingTop: '24px',
    justifyContent: 'space-between',
  },
  propertiesCard: {
    width: '80px',
    height: '80px',
    background: '#F8F8F8',
    borderRadius: '8px',
    // marginRight: "21px",
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '21px',
    flexFlow: 'column',
    padding: '7px',
  },
  propertiesIcon: {
    display: 'block',
    marginBottom: '11px',
    // "& path":{
    //   fill:"#5C5A61 !important",
    // },
  },
  properties: {
    color: '#252427',
    textAlign: 'center',
  },
  // description: {
  //     color: "#5C5A61",
  //     marginBottom: "32px"
  // },
  nutritionBlock: {
    paddingTop: '32px',
  },
  subHeading: {
    color: '#252427',
    display: 'block',
    marginBottom: '24px',
  },
  nutritionDetails: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexFlow: 'column',
    marginRight: '35px',
  },
  nutritionDetailsWrap: {
    display: 'flex',
    // justifyContent: "center",
    alignItems: 'center',
  },
  nutritionTitle: {
    color: '#5C5A61',
    display: 'block',
    marginBottom: '7px',
  },
  nutritionCircle: {
    position: 'relative',
    display: 'inline-block',
  },
  circleValue: {
    color: '#40916C',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%)',
  },
  ingredientsWrap: {
    paddingTop: '35px',
    marginBottom: '30px',
    '& li': {
      display: 'grid',
      gridTemplateColumns: '7fr 3fr',
    },
  },
  headerWrap: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '30px',
  },
  headerText: {
    color: '#252427',
  },
  buttonWrap: {
    background: '#252427',
    padding: '12px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: '6px',
  },
  buttonText: {
    color: '#fff',
    marginRight: '8px',
    display: 'inline-block',
  },
  buttonGrp: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    minWidth: '83px',
  },
  actionBtn: {
    display: 'flex',
    height: '28px',
    width: '28px',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#5C5A61',
    borderRadius: '6px',
    color: '#fff',
    cursor: 'pointer',
  },
  btnText: {
    color: '#fff',
    display: 'inline-block',
    padding: '0 5px',
  },
  listWrap: {
    listStyle: 'none',
    padding: '0px',
  },
  listItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  textWrap: {
    display: 'grid',
    // justifyContent: "center",
    gridTemplateColumns: '40px calc(100% - 56px)',
    gridGap: '16px',
    alignItems: 'center',
  },
  listIcon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '40px',
    width: '40px',
    borderRadius: '8px',
    background: '#F5F6F8',
    '&svg': {
      '&path': {
        fill: '#5C5A61!important',
      },
    },
    '& path': {
      fill: '#5C5A61 !important',
    },
  },
  listText: {
    color: '#252427',
  },
  quantity: {
    color: '#5C5A61',
    marginRight: '25px',
    '&.marginRight': {
      marginRight: '5px',
    },
  },
  readMoreBtn: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'end',
    width: '100%',
    // maxWidth: "20%",
    // width: "20%",
    position: 'relative',
    top: '10px',
    '&:focus': {
      outline: 'none !important',
    },
  },

  caloriesCalcBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    margin: '20px 0',
  },
  contentButton: {
    padding: '0 !important',
    justifyContent: 'flex-start !important',
    fontWeight: 600,
    '& svg': {
      height: '20px',
      width: '20px',
      '& path': {
        fill: '#5C5A61 !important',
      },
    },
    '&.rotateArrow': {
      '& svg': { rotate: '180deg' },
    },
  },
  nutrientBox: {
    margin: '20px 0',
  },
  hearder17: {
    color: theme.palette.colors.theme.primary,
    marginBottom: '20px',
  },
  nutrientsRowBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  subContainer: {
    display: 'flex',
    justifyContent: 'end',
    alignItems: 'center',
  },
  dbHeading: {
    display: 'flex',
    gap: '8px',
    color: theme.palette.colors.gray[500],
    wordBreak: 'break-word',
  },
  dbSelect: {
    // width: 'calc(100% - 32px)',
    // float: 'right',
  },
  //popup styles
  mainHeading: {
    color: theme.palette.colors.gray[900],
    margin: '0px 40px 10px 40px',
    textAlign: 'center',
    wordBreak: 'break-all',
  },
  prescriptionFooter: {
    gap: '10px !important',
    boxShadow: 'none !important',
    justifyContent: 'center !important',
    backgroundColor: 'transparent !important',
    display: 'grid',
    gridTemplateColumns: '100px 100px',
    alignItems: 'stretch',
  },
  deleteRecipeFooter: {
    boxShadow: 'none !important',
    // justifyContent: "center",
  },
  btnHeight: {
    height: '44px',
  },
}));
