import { makeStyles } from 'tss-react/mui';
import { IProps } from './NameCard.types';

// TODO jss-to-tss-react codemod: Unable to handle style definition reliably. ArrowFunctionExpression in CSS prop.
// TODO jss-to-tss-react codemod: Unable to handle style definition reliably. ArrowFunctionExpression in CSS prop.
// TODO jss-to-tss-react codemod: Unable to handle style definition reliably. ArrowFunctionExpression in CSS prop.
// TODO jss-to-tss-react codemod: Unable to handle style definition reliably. ArrowFunctionExpression in CSS prop.
// TODO jss-to-tss-react codemod: usages of this hook outside of this file will not be converted.
export const useStyles = makeStyles<IProps>()(
  (theme, { roundedBorder, isClientSelected, isExtend, justifyContentCaption, isEventSelected }) => ({
    mainContainer: {
      display: 'flex',
      backgroundColor: isClientSelected || isEventSelected ? theme.palette.colors.system.white : theme.palette.colors.gray[50],
      borderBottom: '2px solid #fff',
      cursor: 'pointer',
      borderRadius: roundedBorder ? '8px' : '0px',
      position: 'relative',
      height: isExtend ? '192px' : '',
      '& *': { boxSizing: 'border-box' },
    },
    bannerDiv: {
      width: '6px',
      height: 'inherit',
    },
    contentContainer: {
      padding: '12px 20px 12px 14px',
      flex: 1,
    },
    profilecontainer: {
      marginRight: '12px',
    },
    nameCardHeader: {
      marginBottom: '8px',
      display: 'grid',
      gridTemplateColumns: '60px 1fr',
      height: '64px',
    },
    nameContainer: {
      flex: 1,
    },
    nameContainerHead: {
      display: 'grid',
      alignItems: 'center',
      marginBottom: '8px',
      gridTemplateColumns: '1fr auto',
    },
    nameConatinerHeadMenu: {
      flex: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '10px',
    },
    overlayStyle: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 2,
      position: 'absolute',
      backgroundColor: 'rgba(37, 36, 39, 0.5)',
      cursor: 'pointer',
      borderRadius: roundedBorder ? '8px' : '0px',
      '& .ticIconStyle': {
        right: '24px',
        top: '50%',
        zIndex: 3,
        position: 'absolute',
        transform: 'translateY(-50%)',
      },
    },
    avatarCon: {
      display: 'flex',
      alignItems: 'center',
      width: '100%',
      height: '100%',
    },
    profilePic: {
      borderRadius: '50%',
      height: '44px',
      width: '44px',
      position: 'relative',
      fontSize: '12px',
      fontFamily: 'Graphik',
      fontWeight: 400,
      color: theme.palette.colors.system.white,
      backgroundColor: theme.palette.colors.gray[100],
    },
    profileDiv: {
      height: '47px',
      width: '47px',
      position: 'relative',
    },
    profilegroupCon: {
      display: 'flex',
      justifyContent: 'end',
      alignItems: 'center',
    },
    logoIcon: {
      display: 'block',
      height: '18px',
      width: '18px',
      position: 'absolute',
      top: '28px',
      zIndex: 1,
      left: '28px',
    },
    dotIconDiv: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'end',
    },
    DotsDiv: {
      padding: '5px 4px',
      display: 'flex',
      alignItems: 'center',
      backgroundColor: !isClientSelected ? theme.palette.colors.system.white : theme.palette.colors.gray[50],
      borderRadius: '8px',
      boxShadow: 'inset 0px 0px 1px rgba(0, 0, 0, 0.25)',
      marginRight: '2px',
    },
    captionCon: {
      padding: '4px 8px',
      backgroundColor: isClientSelected ? theme.palette.colors.gray[50] : theme.palette.colors.system.white,
      borderRadius: '4px',
      width: 'fit-content',
      color: '#5C5A61',
      overflow: 'hidden',
      margin: '0px',
      display: '-webkit-box',
      WebkitLineClamp: 1,
      WebkitBoxOrient: 'vertical',
      height: '24px',
      //lineHeight: 'unset !important',
      lineHeight: '19px',
      maxWidth: '100%',
      wordBreak: 'break-word',
    },
    timelineWrapper: {
      height: '16px',
    },
    userNametext: {
      color: theme.palette.colors.gray[900],
      overflow: 'hidden',
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis',
      fontWeight: 600,
      flex: 1,
      marginRight: '6px',
      wordBreak: 'break-word',
    },
    nameContainerDesc: {
      display: 'grid',
      gridAutoFlow: 'column',
      overflow: 'hidden',
      justifyContent: justifyContentCaption || 'flex-start',
      alignItems: 'center',
      gap: '10px',
    },
    leftBox: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
    },
    captionStyle: {
      padding: '4px 10px',
      height: '20px',
      background: theme.palette.colors.theme.primary,
      borderRadius: '4px',
      boxSizing: 'border-box',
      color: theme.palette.colors.system.white,
      // maxWidth: "fit-content",
    },
    iconBox: {
      height: '24px',
      width: '24px',
      padding: '5px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '50%',
      backgroundColor: theme.palette.colors.system.white,
    },
    nameContainerExtended: {
      display: 'grid',
      gridTemplateColumns: '60px 1fr auto',
      marginBottom: '8px',
    },
    discriptionStyle: {
      width: 'fit-content',
      color: theme.palette.colors.gray[400],
      overflow: 'hidden',
      display: '-webkit-box',
      WebkitLineClamp: 1,
      WebkitBoxOrient: 'vertical',
      height: '24px',
      lineHeight: 'unset !important',
      paddingLeft: '10px',
    },
    timeStyle: {
      color: theme.palette.colors.gray[400],
    },
    extentedIconBox: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '10px',
      marginTop: '15px',
    },
    extentedIconBoxLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
    },
    extentedIconBoxRight: {},
    participants: {
      marginLeft: 'auto',
      width: 'fit-content',
    },
    participantPic: {
      borderRadius: '50%',
      height: '24px',
      width: '24px',
      position: 'relative',
      fontSize: '12px',
      fontFamily: 'Graphik',
      fontWeight: 400,
      color: theme.palette.colors.system.white,
      backgroundColor: theme.palette.colors.gray[500],
      border: `1px solid ${theme.palette.colors.system.white}`,
    },
    participantGroup: {
      '& .MuiAvatar-colorDefault': {
        color: theme.palette.colors.system.white,
        backgroundColor: theme.palette.colors.gray[500],
      },
      '& .MuiAvatarGroup-root': {
        justifyContent: 'end',
      },
      '& .MuiAvatar-root': {
        width: '24px',
        height: '24px',
        fontSize: '12px',
        zIndex: '6 !important',
        border: `1px solid ${theme.palette.colors.system.white}`,
        '&::last-of-type': {
          backgroundColor: `${theme.palette.colors.gray[100]} !important`,
          color: `${theme.palette.colors.theme.primary} !important`,
        },
      },
    },
  })
);
