import { makeStyles } from 'tss-react/mui';

export const useStyles = makeStyles()((theme) => ({
  cardContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    position: 'relative',
    width: '100%',
    padding: '12px 20px',
    borderRadius: '8px',
    backgroundColor: theme.palette.colors.gray[50],
    boxSizing: 'border-box',
  },
  iconTitle: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
  },
  muiselectStyle: {
    '& .MuiInputBase-root': {
      marginTop: '0 !important',
    },
  },
  cardSelectSection: {
    display: 'grid',
    gap: '10px',
    gridAutoFlow: 'column',
    alignItems: 'center',
    gridTemplateColumns: '1fr 80px',
    boxSizing: 'border-box',
  },
  profileSection: {
    position: 'relative',
    display: 'flex',
  },
  tenantIcon: {
    display: 'flex',
    position: 'absolute',
    right: 0,
    bottom: 0,
    zIndex: 1,
    translate: '50% 0',
  },
  profilePic: {
    borderRadius: '50%',
    height: '40px',
    width: '40px',
    color: theme.palette.colors.theme.primary,
    backgroundColor: theme.palette.colors.gray[100],
    fontSize: '12px',
    fontWeight: 600,
  },
  profileContentSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  textPrimary: {
    color: theme.palette.colors.theme.primary,
    width: '100%',
    overflow: 'hidden',
    wordBreak: 'break-word',
    display: '-webkit-box',
    WebkitLineClamp: 1,
    WebkitBoxOrient: 'vertical',
  },
  sublabel: {
    color: theme.palette.colors.gray[500],
    maxWidth: 'fit-content',
    borderRadius: '4px',
    overflow: 'hidden',
    wordBreak: 'break-word',
    display: '-webkit-box',
    WebkitLineClamp: 1,
    WebkitBoxOrient: 'vertical',
  },
  selectedSection: {
    cursor: 'pointer',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    background: 'rgba(37,36,39,0.5)',
    borderRadius: 'inherit',
  },
  checkIconDIv: {
    top: '50%',
    right: '20px',
    position: 'absolute',
    translate: '0-50%',
    display: 'flex',
  },
  checkFlexbox: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    minWidth: 'fit-content',
    justifySelf: 'self-end',
  },
  errorText: {
    color: theme.palette.colors.red[700],
  },
  errorTextMessage: {
    borderTop: `1px solid ${theme.palette.colors.gray[100]}`,
    paddingTop: '8px',
    color: theme.palette.colors.red[700],
  },
}));
